"""Typed, lossless parser and analysis layer for Claude Code session transcripts.

Besides this package-level surface, the ``models``, ``report.views``, and ``types``
modules are stable import targets for the full record/block/view vocabulary.
"""

from __future__ import annotations

from .cost.ledger import DayCost, LedgerRow, ModelCost, ProjectLedger, build_ledger
from .cost.pricing import (
    EXAMPLE_PRICING,
    FAMILY_PRICING,
    CostBreakdown,
    ModelPrice,
    PriceTable,
    cost_breakdown_for,
    cost_for,
    family_of,
    price_for_family,
    price_for_model,
    price_for_usage,
    request_cost,
)
from .models import (
    RECORD_ADAPTER,
    AssistantRecord,
    Attachment,
    CacheCreation,
    ContentBlock,
    Record,
    SnakeModel,
    TextBlock,
    ToolUseBlock,
    Usage,
    UserRecord,
)
from .parsing.parse import ParseFailure, iter_records, parse_line
from .parsing.tail import TailBatch, TailRecord, tail_records
from .parsing.tools import (
    MODELED_INPUT_TOOLS,
    MODELED_RESULT_TOOLS,
    TOOL_INPUT_ADAPTERS,
    TOOL_RESULT_ADAPTERS,
    parse_tool_input,
    parse_tool_result,
    result_tool_name,
    tool_name_index,
)
from .report.audit import SchemaAudit, audit_files, format_audit
from .report.export import ExportSpec, export
from .report.investigation import (
    InvestigationReport,
    ToolCallStat,
    build_investigation,
    render_investigation_markdown,
)
from .report.render import (
    format_cost_summary,
    format_queries,
    format_session_list,
    format_timeline,
)
from .report.views import (
    CostSummary,
    ModelUsage,
    SessionInfo,
    TextPart,
    ThinkingPart,
    TimelineEntry,
    TimelinePart,
    ToolCall,
    ToolResultPart,
    ToolUsePart,
    message_text,
    tool_result_text,
)
from .session import (
    DEFAULT_PROJECTS_ROOT,
    Session,
    iter_raw,
    load_project,
    request_key,
    resolve_session_file,
    session_files,
)

__all__ = [
    "DEFAULT_PROJECTS_ROOT",
    "EXAMPLE_PRICING",
    "FAMILY_PRICING",
    "MODELED_INPUT_TOOLS",
    "MODELED_RESULT_TOOLS",
    "RECORD_ADAPTER",
    "TOOL_INPUT_ADAPTERS",
    "TOOL_RESULT_ADAPTERS",
    "AssistantRecord",
    "Attachment",
    "CacheCreation",
    "ContentBlock",
    "CostBreakdown",
    "CostSummary",
    "DayCost",
    "ExportSpec",
    "InvestigationReport",
    "LedgerRow",
    "ModelCost",
    "ModelPrice",
    "ModelUsage",
    "ParseFailure",
    "PriceTable",
    "ProjectLedger",
    "Record",
    "SchemaAudit",
    "Session",
    "SessionInfo",
    "SnakeModel",
    "TailBatch",
    "TailRecord",
    "TextBlock",
    "TextPart",
    "ThinkingPart",
    "TimelineEntry",
    "TimelinePart",
    "ToolCall",
    "ToolCallStat",
    "ToolResultPart",
    "ToolUseBlock",
    "ToolUsePart",
    "Usage",
    "UserRecord",
    "audit_files",
    "build_investigation",
    "build_ledger",
    "cost_breakdown_for",
    "cost_for",
    "export",
    "family_of",
    "format_audit",
    "format_cost_summary",
    "format_queries",
    "format_session_list",
    "format_timeline",
    "iter_raw",
    "iter_records",
    "load_project",
    "message_text",
    "parse_line",
    "parse_tool_input",
    "parse_tool_result",
    "price_for_family",
    "price_for_model",
    "price_for_usage",
    "render_investigation_markdown",
    "request_cost",
    "request_key",
    "resolve_session_file",
    "result_tool_name",
    "session_files",
    "tail_records",
    "tool_name_index",
    "tool_result_text",
]
